name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==5.13.2 pillow pygame

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --uac-admin --collect-all tkinter --collect-all pygame --add-data "lock.jpg;." --add-data "screamer.jpg;." --add-data "scary_very.mp3;." --name PyScriptServer main.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: PyScriptServer-exe
        path: dist/PyScriptServer.exe
